In [1]:
import pandas as pd

In [2]:
with_strat = pd.read_csv('MaSac transcripts with strategy annotations.csv')
with_strat.head()

,Transcript,English Translation,Monolingual English?,Type of code-switching,Intersentential code-switch?
0,Nahi.,No.,False,-1,NaN
1,"Aah! Ye dekh, hai na same to same!","Ahh! Look at this, isn't it same to same?",False,I,NaN
2,Mummy ji 7500 chalenge?,"Mom, will 7500 work?",False,-1,NaN
3,No... 10000.,No...10000.,False,I,NaN
4,"Chaliye, na aapki na meri, 8500... haan?","Come on, neither yours nor mine, 8500... yes?",False,-1,NaN

In [18]:
with_paths = pd.read_csv('masac_data_compiled.csv')
with_paths.head()

,Unnamed: 0,name,Transcript,English Translation,LID_tags,Language,spectrogram
0,0,train_337_0.wav,Fridge repair ho gaya! Start kar raha hu.,Fridge repaired! Starting.,"['EN', 'EN', 'EN', 'HI', 'OTHER', 'EN', 'HI', ...",CSW,train_337_0.png
1,1,train_91_2.wav,Mendhak kaam aaega?,Will the frog be useful?,"['HI', 'HI', 'HI', 'OTHER']",HI,train_91_2.png
2,2,train_213_4.wav,haan! jab sahil ko pta chalega tab wo tumhe co...,"Yes! When Sahil comes to know about this, he w...","['HI', 'OTHER', 'HI', 'HI', 'HI', 'HI', 'HI', ...",CSW,train_213_4.png
3,3,train_249_3.wav,Aur Sahil kal wapas aa gaya toh?,And if Sahil came back tomorrow?,"['HI', 'HI', 'HI', 'HI', 'HI', 'HI', 'HI', 'OT...",HI,train_249_3.png
4,4,train_193_0.wav,"Well, he was a darling.","Well, he was a darling.","['EN', 'OTHER', 'EN', 'EN', 'EN', 'EN', 'OTHER']",EN,train_193_0.png

In [19]:
with_paths = with_paths[['name', 'Transcript', 'English Translation', 'LID_tags', 'Language']]
with_paths.head()

,name,Transcript,English Translation,LID_tags,Language
0,train_337_0.wav,Fridge repair ho gaya! Start kar raha hu.,Fridge repaired! Starting.,"['EN', 'EN', 'EN', 'HI', 'OTHER', 'EN', 'HI', ...",CSW
1,train_91_2.wav,Mendhak kaam aaega?,Will the frog be useful?,"['HI', 'HI', 'HI', 'OTHER']",HI
2,train_213_4.wav,haan! jab sahil ko pta chalega tab wo tumhe co...,"Yes! When Sahil comes to know about this, he w...","['HI', 'OTHER', 'HI', 'HI', 'HI', 'HI', 'HI', ...",CSW
3,train_249_3.wav,Aur Sahil kal wapas aa gaya toh?,And if Sahil came back tomorrow?,"['HI', 'HI', 'HI', 'HI', 'HI', 'HI', 'HI', 'OT...",HI
4,train_193_0.wav,"Well, he was a darling.","Well, he was a darling.","['EN', 'OTHER', 'EN', 'EN', 'EN', 'EN', 'OTHER']",EN

In [20]:
len(with_paths) == len(with_strat)

False

In [21]:
len(with_paths)

6476

In [22]:
len(with_strat)

9079

In [29]:
with_path_transcript = list(with_paths['Transcript'])
with_strat_transcript = list(with_strat['Transcript'])
strat_annotations = list(with_strat['Type of code-switching'])

In [30]:
path_linked_annotations = []

In [31]:
for transcript_p in with_path_transcript:
    found = False
    for i in range(len(with_strat_transcript)):
        transcript_a = with_strat_transcript[i]
        if transcript_p == transcript_a:
            path_linked_annotations.append(strat_annotations[i])
            found = True
            break
    if found == False:
        path_linked_annotations.append('TODO')

In [32]:
len(path_linked_annotations)

6476

In [33]:
path_linked_annotations.count('TODO')

21

In [37]:
from collections import defaultdict

In [38]:
annotations_dict = defaultdict()

In [39]:
for label in path_linked_annotations:
    if label not in annotations_dict.keys():
        annotations_dict[label] = 1
    else:
        annotations_dict[label] += 1

annotations_dict

defaultdict(None,
            {'I': 2898,
             '-1': 2994,
             'A, I': 150,
             'A': 197,
             'I, A': 136,
             'TODO': 21,
             'O': 69,
             'A,  I': 2,
             'A, O': 2,
             'O, A': 4,
             'I, A, O': 1,
             'O, I': 1,
             '--1': 1})

In [40]:
with_paths['Type of code-switching'] = path_linked_annotations
with_paths.head()

,name,Transcript,English Translation,LID_tags,Language,Type of code-switching
0,train_337_0.wav,Fridge repair ho gaya! Start kar raha hu.,Fridge repaired! Starting.,"['EN', 'EN', 'EN', 'HI', 'OTHER', 'EN', 'HI', ...",CSW,I
1,train_91_2.wav,Mendhak kaam aaega?,Will the frog be useful?,"['HI', 'HI', 'HI', 'OTHER']",HI,-1
2,train_213_4.wav,haan! jab sahil ko pta chalega tab wo tumhe co...,"Yes! When Sahil comes to know about this, he w...","['HI', 'OTHER', 'HI', 'HI', 'HI', 'HI', 'HI', ...",CSW,I
3,train_249_3.wav,Aur Sahil kal wapas aa gaya toh?,And if Sahil came back tomorrow?,"['HI', 'HI', 'HI', 'HI', 'HI', 'HI', 'HI', 'OT...",HI,-1
4,train_193_0.wav,"Well, he was a darling.","Well, he was a darling.","['EN', 'OTHER', 'EN', 'EN', 'EN', 'EN', 'OTHER']",EN,-1

In [41]:
with_paths.to_csv('masac_data_compiled_with_strategies.csv')